services:
  app:
    image: hello-front-dev
    build:
      context: . 
      dockerfile: dev.Dockerfile 
    volumes:
      - ./:/usr/src/app 
    ports:
      - 3003:3003
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
    container_name: hello-front-dev
  